### ISSUE TITLE
what versions of the libraries?

### ISSUE THREAD

**Issue by astraw** [dp4846/conn2eff#1]
I'm looking forward to digging in to this and thanks for releasing it. However, I am hitting various warnings and errors presumably related to library version incompatibilities:

```
andrew@monster data % python connectome_data.py
/Users/andrew/Documents/other-peoples-src/conn2eff/data/connectome_data.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_connections['nt_sign'][df_connections['p_exc']>=0.5] = 1
/Users/andrew/Documents/other-peoples-src/conn2eff/data/connectome_data.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_connections['nt_sign'][df_connections['p_exc']<0.5] = -1
```

```
andrew@monster fig4 % python fig4_eigencircuits.py
/Users/andrew/anaconda3/envs/wm01-dragon/lib/python3.11/site-packages/matplotlib/cbook.py:1699: ComplexWarning: Casting complex values to real discards the imaginary part
  return math.isfinite(val)
/Users/andrew/anaconda3/envs/wm01-dragon/lib/python3.11/site-packages/matplotlib/cbook.py:1345: ComplexWarning: Casting complex values to real discards the imaginary part
  return np.asarray(x, float)
Traceback (most recent call last):
  File "/Users/andrew/Documents/other-peoples-src/conn2eff/scripts/figs/fig4/fig4_eigencircuits.py", line 147, in <module>
    ax2.set_xticks(np.arange(0, 50 + dt, dt), fontsize=fontsize_tick)
  File "/Users/andrew/anaconda3/envs/wm01-dragon/lib/python3.11/site-packages/matplotlib/axes/_base.py", line 73, in wrapper
    return get_method(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/anaconda3/envs/wm01-dragon/lib/python3.11/site-packages/matplotlib/axis.py", line 2134, in set_ticks
    raise ValueError(
ValueError: Incorrect use of keyword argument 'fontsize'. Keyword arguments other than 'minor' modify the text labels and can only be used if 'labels' are passed as well.
```

I tried Python 3.11.7, pandas 2.1.4 and matplotlib 3.8.0, but I guess you are using something else. What versions of the libraries should use?

**Comment by dp4846** [comment]
Thanks for checking it out and indicating these problems. When I have some time I will better document this. For now:
Python version: 3.9.19 
pandas version: 1.5.3
matplotlib version: 3.6.2

**Comment by astraw** [comment]
Thanks for the quick response. Here are the commands I used:

```shell
conda create -n conn2eff python=3.9
conda activate conn2eff
conda install pandas=1.5.3 # This also resulted in numpy 1.26.4 being installed.
conda install matplotlib=3.6.2
conda install scipy # This installed 1.13.1.
conda install tqdm # This installed 4.66.5.
```

And from there `fig4_eigencircuits.py` run just fine.
